### ISSUE TITLE
Brainstorm guiding questions about the data

### ISSUE THREAD

**Issue by chenkh1** [VandyDataScience/united-way#2]
When analyzing conversion trends, both land type and time will ideally be considered. For instance, possible questions that could be asked of the data include:

 • From 2001 to 2019, was Deciduous Forest more likely to convert to developed land than Cultivated Crops? 

• Where has land converted more recently (e.g. from 2016-2019 vs. from 2001-2019)? 

Once these past conversions have been identified, algorithms to predict future conversion can be developed. Ideally, there would be multiple future scenarios projected, e.g. likely conversion by 2030, 2040, 2050, 2060, 2070 etc.

**Comment by amandaxzhou** [comment]
We could consider recently (e.g. 2001-2019) which specific type of land has been more heavily affected than another and if future scenarios would show patterns that continuously follow that trend?
